name: run the workflow
on:
  repository_dispatch:
    types: [trigger-event]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: use an action for trigger
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: print trigger details
      run: echo ${{ github.event.client_payload.github.action}}
